// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZu20Phz3QcAy5EjfG1mnoeAGSnrlXII',
    appId: '1:163399038838:web:27e99c445775d16132ec57',
    messagingSenderId: '163399038838',
    projectId: 'session-pass',
    authDomain: 'session-pass.firebaseapp.com',
    storageBucket: 'session-pass.firebasestorage.app',
    measurementId: 'G-TCZGJXHSDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoHo8jKhI1p94DeggV3v8eejrD1YOeiw',
    appId: '1:163399038838:android:e64835cb6fc0efca32ec57',
    messagingSenderId: '163399038838',
    projectId: 'session-pass',
    storageBucket: 'session-pass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAg33ZIoqSXdKaBk28cywwFI5uIK71E1Q',
    appId: '1:163399038838:ios:c61dd6de190df07c32ec57',
    messagingSenderId: '163399038838',
    projectId: 'session-pass',
    storageBucket: 'session-pass.firebasestorage.app',
    iosBundleId: 'com.example.sessionPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAg33ZIoqSXdKaBk28cywwFI5uIK71E1Q',
    appId: '1:163399038838:ios:c61dd6de190df07c32ec57',
    messagingSenderId: '163399038838',
    projectId: 'session-pass',
    storageBucket: 'session-pass.firebasestorage.app',
    iosBundleId: 'com.example.sessionPass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlZu20Phz3QcAy5EjfG1mnoeAGSnrlXII',
    appId: '1:163399038838:web:3770cceef6fd680332ec57',
    messagingSenderId: '163399038838',
    projectId: 'session-pass',
    authDomain: 'session-pass.firebaseapp.com',
    storageBucket: 'session-pass.firebasestorage.app',
    measurementId: 'G-QXLV02E0KR',
  );
}
